packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  '@grpc/grpc-js': '1.14.4'
  'form-data': '4.0.6'
  'multer': '2.2.0'
  '@nestjs/platform-express>multer': '2.2.0'
  '@opentelemetry/core': '2.8.0'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': set this to true or false
  '@swc/core': true
  cpu-features: true
  protobufjs: true
  sharp: true
  ssh2: true
  unrs-resolver: true
