// Empty per-origin catalogs — populated context-by-context in Wave 2/3/4 of TD23.
// Each union, not just the object, is what error base-class constructors type their
// `code` param against (TD23 §9) — a code outside its origin's union is a compile error.

export const BookingErrorCode = {
  SERVICE_NOT_FOUND: 'BOOKING_SERVICE_NOT_FOUND',
  SERVICE_DEACTIVATED: 'BOOKING_SERVICE_DEACTIVATED',
  CLOSURE_DATE_IN_PAST: 'BOOKING_CLOSURE_DATE_IN_PAST',
  SCHEDULE_CLOSURE_NOT_FOUND: 'BOOKING_SCHEDULE_CLOSURE_NOT_FOUND',
  SCHEDULE_ALREADY_CLOSED: 'BOOKING_SCHEDULE_ALREADY_CLOSED',
  OPENING_DATE_IN_PAST: 'BOOKING_OPENING_DATE_IN_PAST',
  DAY_ALREADY_OPEN_IN_SETTINGS: 'BOOKING_DAY_ALREADY_OPEN_IN_SETTINGS',
  SCHEDULE_OPENING_ALREADY_EXISTS: 'BOOKING_SCHEDULE_OPENING_ALREADY_EXISTS',
  SCHEDULE_OPENING_NOT_FOUND: 'BOOKING_SCHEDULE_OPENING_NOT_FOUND',
  AVAILABILITY_DATE_IN_PAST: 'BOOKING_AVAILABILITY_DATE_IN_PAST',
  AVAILABILITY_RANGE_INVALID: 'BOOKING_AVAILABILITY_RANGE_INVALID',
  NOT_FOUND: 'BOOKING_NOT_FOUND',
  LINE_REQUIRED: 'BOOKING_LINE_REQUIRED',
  PICKUP_ADDRESS_REQUIRED: 'BOOKING_PICKUP_ADDRESS_REQUIRED',
  INVALID_TRANSITION: 'BOOKING_INVALID_TRANSITION',
  SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  SERVICE_NOT_ACTIVE: 'BOOKING_SERVICE_NOT_ACTIVE',
  SERVICE_NOT_IN_TENANT: 'BOOKING_SERVICE_NOT_IN_TENANT',
  CANCELLATION_WINDOW_EXPIRED: 'BOOKING_CANCELLATION_WINDOW_EXPIRED',
  CUSTOMER_NOT_FOUND: 'BOOKING_CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_NOT_SET: 'BOOKING_CUSTOMER_PHONE_NOT_SET',
  REJECTION_REASON_TOO_SHORT: 'BOOKING_REJECTION_REASON_TOO_SHORT',
  INFO_MESSAGE_TOO_SHORT: 'BOOKING_INFO_MESSAGE_TOO_SHORT',
  FORBIDDEN: 'BOOKING_FORBIDDEN',
  SCHEDULED_IN_PAST: 'BOOKING_SCHEDULED_IN_PAST',
  SCHEDULED_AT_INVALID: 'BOOKING_SCHEDULED_AT_INVALID',
  COMPLETE_LINES_INCOMPLETE: 'BOOKING_COMPLETE_LINES_INCOMPLETE',
  PHOTO_NOT_UPLOADED: 'BOOKING_PHOTO_NOT_UPLOADED',
  DISCOUNT_NOT_AVAILABLE: 'BOOKING_DISCOUNT_NOT_AVAILABLE',
  DISCOUNT_DISABLED: 'BOOKING_DISCOUNT_DISABLED',
  DISCOUNT_MISMATCH: 'BOOKING_DISCOUNT_MISMATCH',
  DISCOUNT_EXCEEDS_TOTAL: 'BOOKING_DISCOUNT_EXCEEDS_TOTAL',
  TENANT_ID_REQUIRED: 'BOOKING_TENANT_ID_REQUIRED',
  CREATED_BY_REQUIRED: 'BOOKING_CREATED_BY_REQUIRED',
  SERVICE_NAME_REQUIRED: 'BOOKING_SERVICE_NAME_REQUIRED',
  SERVICE_PRICE_INVALID: 'BOOKING_SERVICE_PRICE_INVALID',
  SERVICE_DURATION_INVALID: 'BOOKING_SERVICE_DURATION_INVALID',
  SERVICE_LOYALTY_POINTS_INVALID: 'BOOKING_SERVICE_LOYALTY_POINTS_INVALID',
  CLOSURE_REASON_INVALID: 'BOOKING_CLOSURE_REASON_INVALID',
  CLOSURE_TIME_RANGE_INCOMPLETE: 'BOOKING_CLOSURE_TIME_RANGE_INCOMPLETE',
  TIME_RANGE_FORMAT_INVALID: 'BOOKING_TIME_RANGE_FORMAT_INVALID',
  TIME_RANGE_ORDER_INVALID: 'BOOKING_TIME_RANGE_ORDER_INVALID',
} as const;
export type BookingErrorCode = (typeof BookingErrorCode)[keyof typeof BookingErrorCode];

export const CustomerErrorCode = {
  NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  TENANT_ID_REQUIRED: 'CUSTOMER_TENANT_ID_REQUIRED',
  GOOGLE_OAUTH_ID_REQUIRED: 'CUSTOMER_GOOGLE_OAUTH_ID_REQUIRED',
  EMAIL_INVALID: 'CUSTOMER_EMAIL_INVALID',
  NAME_REQUIRED: 'CUSTOMER_NAME_REQUIRED',
  PHONE_INVALID: 'CUSTOMER_PHONE_INVALID',
} as const;
export type CustomerErrorCode = (typeof CustomerErrorCode)[keyof typeof CustomerErrorCode];

export const StaffErrorCode = {
  NOT_FOUND: 'STAFF_NOT_FOUND',
  ALREADY_ACTIVE: 'STAFF_ALREADY_ACTIVE',
  DEACTIVATED: 'STAFF_DEACTIVATED',
  EMAIL_MISMATCH: 'STAFF_EMAIL_MISMATCH',
  ALREADY_EXISTS: 'STAFF_ALREADY_EXISTS',
  SELF_DEACTIVATION: 'STAFF_SELF_DEACTIVATION',
  SELF_REACTIVATION: 'STAFF_SELF_REACTIVATION',
  LAST_ACTIVE_MANAGER: 'STAFF_LAST_ACTIVE_MANAGER',
  GOOGLE_ACCOUNT_CONFLICT: 'STAFF_GOOGLE_ACCOUNT_CONFLICT',
  TENANT_ID_REQUIRED: 'STAFF_TENANT_ID_REQUIRED',
  EMAIL_INVALID: 'STAFF_EMAIL_INVALID',
  NAME_REQUIRED: 'STAFF_NAME_REQUIRED',
  ROLE_INVALID: 'STAFF_ROLE_INVALID',
  GOOGLE_OAUTH_ID_REQUIRED: 'STAFF_GOOGLE_OAUTH_ID_REQUIRED',
} as const;
export type StaffErrorCode = (typeof StaffErrorCode)[keyof typeof StaffErrorCode];

export const LoyaltyErrorCode = {
  INVALID_POINTS: 'LOYALTY_INVALID_POINTS',
  INSUFFICIENT_POINTS: 'LOYALTY_INSUFFICIENT_POINTS',
  BALANCE_NOT_FOUND: 'LOYALTY_BALANCE_NOT_FOUND',
} as const;
export type LoyaltyErrorCode = (typeof LoyaltyErrorCode)[keyof typeof LoyaltyErrorCode];

export const PlatformErrorCode = {
  SLUG_ALREADY_TAKEN: 'PLATFORM_SLUG_ALREADY_TAKEN',
  TENANT_NOT_FOUND: 'PLATFORM_TENANT_NOT_FOUND',
  TENANT_INACTIVE: 'PLATFORM_TENANT_INACTIVE',
  HOTSITE_NOT_FOUND: 'PLATFORM_HOTSITE_NOT_FOUND',
  HOTSITE_IMAGE_NOT_UPLOADED: 'PLATFORM_HOTSITE_IMAGE_NOT_UPLOADED',
  TENANT_NAME_REQUIRED: 'PLATFORM_TENANT_NAME_REQUIRED',
  TENANT_SLUG_INVALID: 'PLATFORM_TENANT_SLUG_INVALID',
  HOTSITE_NO_ENABLED_MODULES: 'PLATFORM_HOTSITE_NO_ENABLED_MODULES',
  HOTSITE_BRANDING_COLOR_INVALID: 'PLATFORM_HOTSITE_BRANDING_COLOR_INVALID',
  HOTSITE_BRANDING_OPTION_INVALID: 'PLATFORM_HOTSITE_BRANDING_OPTION_INVALID',
  HOTSITE_MODULE_TYPE_INVALID: 'PLATFORM_HOTSITE_MODULE_TYPE_INVALID',
  HOTSITE_SEO_TITLE_TOO_LONG: 'PLATFORM_HOTSITE_SEO_TITLE_TOO_LONG',
  HOTSITE_SEO_DESCRIPTION_TOO_LONG: 'PLATFORM_HOTSITE_SEO_DESCRIPTION_TOO_LONG',
  SETTINGS_CURRENCY_REQUIRED: 'PLATFORM_SETTINGS_CURRENCY_REQUIRED',
  SETTINGS_LANGUAGE_REQUIRED: 'PLATFORM_SETTINGS_LANGUAGE_REQUIRED',
  SETTINGS_CURRENCY_SYMBOL_INVALID: 'PLATFORM_SETTINGS_CURRENCY_SYMBOL_INVALID',
  SETTINGS_DECIMAL_PLACES_INVALID: 'PLATFORM_SETTINGS_DECIMAL_PLACES_INVALID',
  SETTINGS_FIELD_NOT_STRING: 'PLATFORM_SETTINGS_FIELD_NOT_STRING',
  SETTINGS_NOTIFICATION_EMAIL_INVALID: 'PLATFORM_SETTINGS_NOTIFICATION_EMAIL_INVALID',
  SETTINGS_LOYALTY_EXPIRY_DAYS_INVALID: 'PLATFORM_SETTINGS_LOYALTY_EXPIRY_DAYS_INVALID',
  SETTINGS_LOYALTY_EXPIRY_WARNING_DAYS_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_EXPIRY_WARNING_DAYS_INVALID',
  SETTINGS_LOYALTY_EXPIRY_WARNING_TOO_LATE: 'PLATFORM_SETTINGS_LOYALTY_EXPIRY_WARNING_TOO_LATE',
  SETTINGS_LOYALTY_NOTIFICATION_MIN_POINTS_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_NOTIFICATION_MIN_POINTS_INVALID',
  SETTINGS_LOYALTY_POINTS_PER_CURRENCY_UNIT_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_POINTS_PER_CURRENCY_UNIT_INVALID',
  SETTINGS_BOOKING_CANCELLATION_WINDOW_INVALID:
    'PLATFORM_SETTINGS_BOOKING_CANCELLATION_WINDOW_INVALID',
  SETTINGS_BOOKING_MIN_ADVANCE_HOURS_INVALID: 'PLATFORM_SETTINGS_BOOKING_MIN_ADVANCE_HOURS_INVALID',
  SETTINGS_BOOKING_MAX_ADVANCE_DAYS_INVALID: 'PLATFORM_SETTINGS_BOOKING_MAX_ADVANCE_DAYS_INVALID',
  SETTINGS_BOOKING_SERVICE_BUFFER_INVALID: 'PLATFORM_SETTINGS_BOOKING_SERVICE_BUFFER_INVALID',
  SETTINGS_BOOKING_SLOT_GRANULARITY_INVALID: 'PLATFORM_SETTINGS_BOOKING_SLOT_GRANULARITY_INVALID',
  SETTINGS_BOOKING_WELCOME_STAFF_SCREEN_DAYS_INVALID:
    'PLATFORM_SETTINGS_BOOKING_WELCOME_STAFF_SCREEN_DAYS_INVALID',
  SETTINGS_TIMEZONE_INVALID: 'PLATFORM_SETTINGS_TIMEZONE_INVALID',
  SETTINGS_BUSINESS_HOURS_FORMAT_INVALID: 'PLATFORM_SETTINGS_BUSINESS_HOURS_FORMAT_INVALID',
  SETTINGS_BUSINESS_HOURS_ORDER_INVALID: 'PLATFORM_SETTINGS_BUSINESS_HOURS_ORDER_INVALID',
  SETTINGS_BUSINESS_PHONE_INVALID: 'PLATFORM_SETTINGS_BUSINESS_PHONE_INVALID',
  SETTINGS_BUSINESS_EMAIL_INVALID: 'PLATFORM_SETTINGS_BUSINESS_EMAIL_INVALID',
  SETTINGS_SOCIAL_WHATSAPP_INVALID: 'PLATFORM_SETTINGS_SOCIAL_WHATSAPP_INVALID',
} as const;
export type PlatformErrorCode = (typeof PlatformErrorCode)[keyof typeof PlatformErrorCode];

export const AddressErrorCode = {
  POSTAL_CODE_INVALID: 'ADDRESS_POSTAL_CODE_INVALID',
  STATE_INVALID: 'ADDRESS_STATE_INVALID',
  NEIGHBORHOOD_REQUIRED: 'ADDRESS_NEIGHBORHOOD_REQUIRED',
  FIELD_REQUIRED: 'ADDRESS_FIELD_REQUIRED',
} as const;
export type AddressErrorCode = (typeof AddressErrorCode)[keyof typeof AddressErrorCode];

export const CountryCodeErrorCode = {
  FORMAT_INVALID: 'COUNTRY_CODE_FORMAT_INVALID',
  UNSUPPORTED: 'COUNTRY_CODE_UNSUPPORTED',
} as const;
export type CountryCodeErrorCode = (typeof CountryCodeErrorCode)[keyof typeof CountryCodeErrorCode];

export const PhoneErrorCode = {} as const;
export type PhoneErrorCode = (typeof PhoneErrorCode)[keyof typeof PhoneErrorCode];

export const MoneyErrorCode = {} as const;
export type MoneyErrorCode = (typeof MoneyErrorCode)[keyof typeof MoneyErrorCode];

export const SeoErrorCode = {} as const;
export type SeoErrorCode = (typeof SeoErrorCode)[keyof typeof SeoErrorCode];

export const SlugErrorCode = {} as const;
export type SlugErrorCode = (typeof SlugErrorCode)[keyof typeof SlugErrorCode];

export const HexColorErrorCode = {} as const;
export type HexColorErrorCode = (typeof HexColorErrorCode)[keyof typeof HexColorErrorCode];

export const TimezoneErrorCode = {} as const;
export type TimezoneErrorCode = (typeof TimezoneErrorCode)[keyof typeof TimezoneErrorCode];

export const TimeOfDayErrorCode = {} as const;
export type TimeOfDayErrorCode = (typeof TimeOfDayErrorCode)[keyof typeof TimeOfDayErrorCode];

export const EmailErrorCode = {} as const;
export type EmailErrorCode = (typeof EmailErrorCode)[keyof typeof EmailErrorCode];

export const BffErrorCode = {} as const;
export type BffErrorCode = (typeof BffErrorCode)[keyof typeof BffErrorCode];

export const GenericErrorCode = {} as const;
export type GenericErrorCode = (typeof GenericErrorCode)[keyof typeof GenericErrorCode];
