// One per-origin catalog per bounded context / cross-cutting concern (TD23).
// Each union, not just the object, is what error base-class constructors type their
// `code` param against (TD23 §9) — a code outside its origin's union is a compile error.

export const BookingErrorCode = {
  SERVICE_NOT_FOUND: 'BOOKING_SERVICE_NOT_FOUND',
  SERVICE_DEACTIVATED: 'BOOKING_SERVICE_DEACTIVATED',
  CLOSURE_DATE_IN_PAST: 'BOOKING_CLOSURE_DATE_IN_PAST',
  SCHEDULE_CLOSURE_NOT_FOUND: 'BOOKING_SCHEDULE_CLOSURE_NOT_FOUND',
  SCHEDULE_ALREADY_CLOSED: 'BOOKING_SCHEDULE_ALREADY_CLOSED',
  OPENING_DATE_IN_PAST: 'BOOKING_OPENING_DATE_IN_PAST',
  DAY_ALREADY_OPEN_IN_SETTINGS: 'BOOKING_DAY_ALREADY_OPEN_IN_SETTINGS',
  SCHEDULE_OPENING_ALREADY_EXISTS: 'BOOKING_SCHEDULE_OPENING_ALREADY_EXISTS',
  SCHEDULE_OPENING_NOT_FOUND: 'BOOKING_SCHEDULE_OPENING_NOT_FOUND',
  AVAILABILITY_DATE_IN_PAST: 'BOOKING_AVAILABILITY_DATE_IN_PAST',
  AVAILABILITY_RANGE_INVALID: 'BOOKING_AVAILABILITY_RANGE_INVALID',
  NOT_FOUND: 'BOOKING_NOT_FOUND',
  LINE_REQUIRED: 'BOOKING_LINE_REQUIRED',
  PICKUP_ADDRESS_REQUIRED: 'BOOKING_PICKUP_ADDRESS_REQUIRED',
  INVALID_TRANSITION: 'BOOKING_INVALID_TRANSITION',
  SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  CONCURRENT_MODIFICATION: 'BOOKING_CONCURRENT_MODIFICATION',
  SERVICE_NOT_ACTIVE: 'BOOKING_SERVICE_NOT_ACTIVE',
  SERVICE_NOT_IN_TENANT: 'BOOKING_SERVICE_NOT_IN_TENANT',
  CANCELLATION_WINDOW_EXPIRED: 'BOOKING_CANCELLATION_WINDOW_EXPIRED',
  CUSTOMER_NOT_FOUND: 'BOOKING_CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_NOT_SET: 'BOOKING_CUSTOMER_PHONE_NOT_SET',
  REJECTION_REASON_TOO_SHORT: 'BOOKING_REJECTION_REASON_TOO_SHORT',
  INFO_MESSAGE_TOO_SHORT: 'BOOKING_INFO_MESSAGE_TOO_SHORT',
  FORBIDDEN: 'BOOKING_FORBIDDEN',
  SCHEDULED_IN_PAST: 'BOOKING_SCHEDULED_IN_PAST',
  SCHEDULED_AT_INVALID: 'BOOKING_SCHEDULED_AT_INVALID',
  COMPLETE_LINES_INCOMPLETE: 'BOOKING_COMPLETE_LINES_INCOMPLETE',
  PHOTO_NOT_UPLOADED: 'BOOKING_PHOTO_NOT_UPLOADED',
  DISCOUNT_NOT_AVAILABLE: 'BOOKING_DISCOUNT_NOT_AVAILABLE',
  DISCOUNT_DISABLED: 'BOOKING_DISCOUNT_DISABLED',
  DISCOUNT_MISMATCH: 'BOOKING_DISCOUNT_MISMATCH',
  DISCOUNT_EXCEEDS_TOTAL: 'BOOKING_DISCOUNT_EXCEEDS_TOTAL',
  TENANT_ID_REQUIRED: 'BOOKING_TENANT_ID_REQUIRED',
  CREATED_BY_REQUIRED: 'BOOKING_CREATED_BY_REQUIRED',
  SERVICE_NAME_REQUIRED: 'BOOKING_SERVICE_NAME_REQUIRED',
  SERVICE_PRICE_INVALID: 'BOOKING_SERVICE_PRICE_INVALID',
  SERVICE_DURATION_INVALID: 'BOOKING_SERVICE_DURATION_INVALID',
  SERVICE_LOYALTY_POINTS_INVALID: 'BOOKING_SERVICE_LOYALTY_POINTS_INVALID',
  CLOSURE_REASON_INVALID: 'BOOKING_CLOSURE_REASON_INVALID',
  CLOSURE_TIME_RANGE_INCOMPLETE: 'BOOKING_CLOSURE_TIME_RANGE_INCOMPLETE',
  TIME_RANGE_FORMAT_INVALID: 'BOOKING_TIME_RANGE_FORMAT_INVALID',
  TIME_RANGE_ORDER_INVALID: 'BOOKING_TIME_RANGE_ORDER_INVALID',
} as const;
export type BookingErrorCode = (typeof BookingErrorCode)[keyof typeof BookingErrorCode];

export const CustomerErrorCode = {
  NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  TENANT_ID_REQUIRED: 'CUSTOMER_TENANT_ID_REQUIRED',
  GOOGLE_OAUTH_ID_REQUIRED: 'CUSTOMER_GOOGLE_OAUTH_ID_REQUIRED',
  EMAIL_INVALID: 'CUSTOMER_EMAIL_INVALID',
  NAME_REQUIRED: 'CUSTOMER_NAME_REQUIRED',
  PHONE_INVALID: 'CUSTOMER_PHONE_INVALID',
} as const;
export type CustomerErrorCode = (typeof CustomerErrorCode)[keyof typeof CustomerErrorCode];

export const StaffErrorCode = {
  NOT_FOUND: 'STAFF_NOT_FOUND',
  ALREADY_ACTIVE: 'STAFF_ALREADY_ACTIVE',
  DEACTIVATED: 'STAFF_DEACTIVATED',
  EMAIL_MISMATCH: 'STAFF_EMAIL_MISMATCH',
  ALREADY_EXISTS: 'STAFF_ALREADY_EXISTS',
  SELF_DEACTIVATION: 'STAFF_SELF_DEACTIVATION',
  SELF_REACTIVATION: 'STAFF_SELF_REACTIVATION',
  LAST_ACTIVE_MANAGER: 'STAFF_LAST_ACTIVE_MANAGER',
  GOOGLE_ACCOUNT_CONFLICT: 'STAFF_GOOGLE_ACCOUNT_CONFLICT',
  TENANT_ID_REQUIRED: 'STAFF_TENANT_ID_REQUIRED',
  EMAIL_INVALID: 'STAFF_EMAIL_INVALID',
  NAME_REQUIRED: 'STAFF_NAME_REQUIRED',
  ROLE_INVALID: 'STAFF_ROLE_INVALID',
  GOOGLE_OAUTH_ID_REQUIRED: 'STAFF_GOOGLE_OAUTH_ID_REQUIRED',
} as const;
export type StaffErrorCode = (typeof StaffErrorCode)[keyof typeof StaffErrorCode];

export const LoyaltyErrorCode = {
  INVALID_POINTS: 'LOYALTY_INVALID_POINTS',
  INSUFFICIENT_POINTS: 'LOYALTY_INSUFFICIENT_POINTS',
  BALANCE_NOT_FOUND: 'LOYALTY_BALANCE_NOT_FOUND',
} as const;
export type LoyaltyErrorCode = (typeof LoyaltyErrorCode)[keyof typeof LoyaltyErrorCode];

export const PlatformErrorCode = {
  SLUG_ALREADY_TAKEN: 'PLATFORM_SLUG_ALREADY_TAKEN',
  TENANT_NOT_FOUND: 'PLATFORM_TENANT_NOT_FOUND',
  TENANT_INACTIVE: 'PLATFORM_TENANT_INACTIVE',
  HOTSITE_NOT_FOUND: 'PLATFORM_HOTSITE_NOT_FOUND',
  HOTSITE_IMAGE_NOT_UPLOADED: 'PLATFORM_HOTSITE_IMAGE_NOT_UPLOADED',
  TENANT_NAME_REQUIRED: 'PLATFORM_TENANT_NAME_REQUIRED',
  TENANT_SLUG_INVALID: 'PLATFORM_TENANT_SLUG_INVALID',
  HOTSITE_NO_ENABLED_MODULES: 'PLATFORM_HOTSITE_NO_ENABLED_MODULES',
  HOTSITE_BRANDING_COLOR_INVALID: 'PLATFORM_HOTSITE_BRANDING_COLOR_INVALID',
  HOTSITE_BRANDING_OPTION_INVALID: 'PLATFORM_HOTSITE_BRANDING_OPTION_INVALID',
  HOTSITE_MODULE_TYPE_INVALID: 'PLATFORM_HOTSITE_MODULE_TYPE_INVALID',
  HOTSITE_SEO_TITLE_TOO_LONG: 'PLATFORM_HOTSITE_SEO_TITLE_TOO_LONG',
  HOTSITE_SEO_DESCRIPTION_TOO_LONG: 'PLATFORM_HOTSITE_SEO_DESCRIPTION_TOO_LONG',
  SETTINGS_CURRENCY_REQUIRED: 'PLATFORM_SETTINGS_CURRENCY_REQUIRED',
  SETTINGS_LANGUAGE_REQUIRED: 'PLATFORM_SETTINGS_LANGUAGE_REQUIRED',
  SETTINGS_CURRENCY_SYMBOL_INVALID: 'PLATFORM_SETTINGS_CURRENCY_SYMBOL_INVALID',
  SETTINGS_DECIMAL_PLACES_INVALID: 'PLATFORM_SETTINGS_DECIMAL_PLACES_INVALID',
  SETTINGS_FIELD_NOT_STRING: 'PLATFORM_SETTINGS_FIELD_NOT_STRING',
  SETTINGS_NOTIFICATION_EMAIL_INVALID: 'PLATFORM_SETTINGS_NOTIFICATION_EMAIL_INVALID',
  SETTINGS_LOYALTY_EXPIRY_DAYS_INVALID: 'PLATFORM_SETTINGS_LOYALTY_EXPIRY_DAYS_INVALID',
  SETTINGS_LOYALTY_EXPIRY_WARNING_DAYS_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_EXPIRY_WARNING_DAYS_INVALID',
  SETTINGS_LOYALTY_EXPIRY_WARNING_TOO_LATE: 'PLATFORM_SETTINGS_LOYALTY_EXPIRY_WARNING_TOO_LATE',
  SETTINGS_LOYALTY_NOTIFICATION_MIN_POINTS_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_NOTIFICATION_MIN_POINTS_INVALID',
  SETTINGS_LOYALTY_POINTS_PER_CURRENCY_UNIT_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_POINTS_PER_CURRENCY_UNIT_INVALID',
  SETTINGS_BOOKING_CANCELLATION_WINDOW_INVALID:
    'PLATFORM_SETTINGS_BOOKING_CANCELLATION_WINDOW_INVALID',
  SETTINGS_BOOKING_MIN_ADVANCE_HOURS_INVALID: 'PLATFORM_SETTINGS_BOOKING_MIN_ADVANCE_HOURS_INVALID',
  SETTINGS_BOOKING_MAX_ADVANCE_DAYS_INVALID: 'PLATFORM_SETTINGS_BOOKING_MAX_ADVANCE_DAYS_INVALID',
  SETTINGS_BOOKING_SERVICE_BUFFER_INVALID: 'PLATFORM_SETTINGS_BOOKING_SERVICE_BUFFER_INVALID',
  SETTINGS_BOOKING_SLOT_GRANULARITY_INVALID: 'PLATFORM_SETTINGS_BOOKING_SLOT_GRANULARITY_INVALID',
  SETTINGS_BOOKING_WELCOME_STAFF_SCREEN_DAYS_INVALID:
    'PLATFORM_SETTINGS_BOOKING_WELCOME_STAFF_SCREEN_DAYS_INVALID',
  SETTINGS_TIMEZONE_INVALID: 'PLATFORM_SETTINGS_TIMEZONE_INVALID',
  SETTINGS_BUSINESS_HOURS_FORMAT_INVALID: 'PLATFORM_SETTINGS_BUSINESS_HOURS_FORMAT_INVALID',
  SETTINGS_BUSINESS_HOURS_ORDER_INVALID: 'PLATFORM_SETTINGS_BUSINESS_HOURS_ORDER_INVALID',
  SETTINGS_BUSINESS_PHONE_INVALID: 'PLATFORM_SETTINGS_BUSINESS_PHONE_INVALID',
  SETTINGS_BUSINESS_EMAIL_INVALID: 'PLATFORM_SETTINGS_BUSINESS_EMAIL_INVALID',
  SETTINGS_SOCIAL_WHATSAPP_INVALID: 'PLATFORM_SETTINGS_SOCIAL_WHATSAPP_INVALID',
  SETTINGS_UPDATE_EMPTY: 'PLATFORM_SETTINGS_UPDATE_EMPTY',
  HOTSITE_UPDATE_EMPTY: 'PLATFORM_HOTSITE_UPDATE_EMPTY',
  FEATURED_PHOTO_PATH_MISMATCH: 'PLATFORM_FEATURED_PHOTO_PATH_MISMATCH',
} as const;
export type PlatformErrorCode = (typeof PlatformErrorCode)[keyof typeof PlatformErrorCode];

export const AddressErrorCode = {
  POSTAL_CODE_INVALID: 'ADDRESS_POSTAL_CODE_INVALID',
  STATE_INVALID: 'ADDRESS_STATE_INVALID',
  NEIGHBORHOOD_REQUIRED: 'ADDRESS_NEIGHBORHOOD_REQUIRED',
  FIELD_REQUIRED: 'ADDRESS_FIELD_REQUIRED',
} as const;
export type AddressErrorCode = (typeof AddressErrorCode)[keyof typeof AddressErrorCode];

export const CountryCodeErrorCode = {
  FORMAT_INVALID: 'COUNTRY_CODE_FORMAT_INVALID',
  UNSUPPORTED: 'COUNTRY_CODE_UNSUPPORTED',
} as const;
export type CountryCodeErrorCode = (typeof CountryCodeErrorCode)[keyof typeof CountryCodeErrorCode];

export const PhoneErrorCode = {
  FORMAT_INVALID: 'PHONE_FORMAT_INVALID',
} as const;
export type PhoneErrorCode = (typeof PhoneErrorCode)[keyof typeof PhoneErrorCode];

export const MoneyErrorCode = {
  AMOUNT_INVALID: 'MONEY_AMOUNT_INVALID',
  CURRENCY_INVALID: 'MONEY_CURRENCY_INVALID',
  CURRENCY_MISMATCH: 'MONEY_CURRENCY_MISMATCH',
} as const;
export type MoneyErrorCode = (typeof MoneyErrorCode)[keyof typeof MoneyErrorCode];

export const SeoErrorCode = {
  TITLE_TOO_LONG: 'SEO_TITLE_TOO_LONG',
  DESCRIPTION_TOO_LONG: 'SEO_DESCRIPTION_TOO_LONG',
} as const;
export type SeoErrorCode = (typeof SeoErrorCode)[keyof typeof SeoErrorCode];

export const SlugErrorCode = {
  FORMAT_INVALID: 'SLUG_FORMAT_INVALID',
} as const;
export type SlugErrorCode = (typeof SlugErrorCode)[keyof typeof SlugErrorCode];

export const HexColorErrorCode = {
  FORMAT_INVALID: 'HEX_COLOR_FORMAT_INVALID',
} as const;
export type HexColorErrorCode = (typeof HexColorErrorCode)[keyof typeof HexColorErrorCode];

export const TimezoneErrorCode = {
  INVALID: 'TIMEZONE_INVALID',
} as const;
export type TimezoneErrorCode = (typeof TimezoneErrorCode)[keyof typeof TimezoneErrorCode];

export const TimeOfDayErrorCode = {
  FORMAT_INVALID: 'TIME_OF_DAY_FORMAT_INVALID',
} as const;
export type TimeOfDayErrorCode = (typeof TimeOfDayErrorCode)[keyof typeof TimeOfDayErrorCode];

export const EmailErrorCode = {
  FORMAT_INVALID: 'EMAIL_FORMAT_INVALID',
} as const;
export type EmailErrorCode = (typeof EmailErrorCode)[keyof typeof EmailErrorCode];

// Genuinely BFF-feature-originated conditions (TD23 Story 11) — guest-token/guard/tenant-lookup
// failures with no backend equivalent. Framework-level guard rejections (JWT/role/tenant-header
// mismatch, unhandled exceptions) live in AuthErrorCode instead — see its own comment below.
export const BffErrorCode = {
  GUEST_TOKEN_MISSING: 'BFF_GUEST_TOKEN_MISSING',
  GUEST_TOKEN_INVALID: 'BFF_GUEST_TOKEN_INVALID',
  GUEST_TOKEN_BOOKING_MISMATCH: 'BFF_GUEST_TOKEN_BOOKING_MISMATCH',
  GUEST_BOOKING_NOT_AWAITING_INFO: 'BFF_GUEST_BOOKING_NOT_AWAITING_INFO',
  TENANT_SLUG_HEADER_REQUIRED: 'BFF_TENANT_SLUG_HEADER_REQUIRED',
  TENANT_LOOKUP_INCONSISTENT: 'BFF_TENANT_LOOKUP_INCONSISTENT',
  STAFF_NOT_REGISTERED_IN_TENANT: 'BFF_STAFF_NOT_REGISTERED_IN_TENANT',
  CUSTOMER_NOT_REGISTERED_IN_TENANT: 'BFF_CUSTOMER_NOT_REGISTERED_IN_TENANT',
  DEV_AUTH_UNAVAILABLE: 'BFF_DEV_AUTH_UNAVAILABLE',
  UPSTREAM_UNAVAILABLE: 'BFF_UPSTREAM_UNAVAILABLE',
} as const;
export type BffErrorCode = (typeof BffErrorCode)[keyof typeof BffErrorCode];

// Framework/guard-level fallbacks (TD23 Story 11, TD23 §3's "framework fallback" bucket) — not
// business-domain errors. Fires on every request that fails JwtAuthGuard/RolesGuard/TenantGuard,
// or hits ErrorInterceptor's last-resort catch-all. One union, not folded into GenericErrorCode
// (reserved for VO-less Zod validation rules — a different kind of gap) or BffErrorCode (reserved
// for BFF-feature-originated conditions with a specific business meaning).
export const AuthErrorCode = {
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  TENANT_MISMATCH: 'AUTH_TENANT_MISMATCH',
  INTERNAL_ERROR: 'AUTH_INTERNAL_ERROR',
} as const;
export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];

// Backs Zod validation rules with no owning VO (Story 9/10) — a small closed set reused
// across many fields via `field`/`params`, not one bespoke code per call site. A rule that
// duplicates a VO's own check must reuse that VO's code instead (see
// docs/ENGINEERING_RULES.md § Single source of truth for a validation rule's code).
export const GenericErrorCode = {
  FIELD_REQUIRED: 'GENERIC_FIELD_REQUIRED',
  VALUE_TOO_SHORT: 'GENERIC_VALUE_TOO_SHORT',
  VALUE_TOO_LONG: 'GENERIC_VALUE_TOO_LONG',
  VALUE_OUT_OF_RANGE: 'GENERIC_VALUE_OUT_OF_RANGE',
  FORMAT_INVALID: 'GENERIC_FORMAT_INVALID',
  // Enum/union/unrecognized-key mismatches — value isn't one of an allowed set/shape.
  VALUE_INVALID: 'GENERIC_VALUE_INVALID',
} as const;
export type GenericErrorCode = (typeof GenericErrorCode)[keyof typeof GenericErrorCode];

// Union of every catalogued error code across every origin (domain, VO, BFF, auth, generic) —
// the compile-time constraint for throwProblemDetail (packages/nestjs-http). Keeps its
// governance promise (an uncatalogued code fails to compile) global instead of per-context,
// while each call site still narrows to its own specific code type by inference (from
// `err.code` on a typed domain error, or from an enum member reference) — this union only
// rejects strings that aren't a member of any catalogue at all.
export type AnyErrorCode =
  | BookingErrorCode
  | CustomerErrorCode
  | StaffErrorCode
  | LoyaltyErrorCode
  | PlatformErrorCode
  | AddressErrorCode
  | CountryCodeErrorCode
  | PhoneErrorCode
  | MoneyErrorCode
  | SeoErrorCode
  | SlugErrorCode
  | HexColorErrorCode
  | TimezoneErrorCode
  | TimeOfDayErrorCode
  | EmailErrorCode
  | BffErrorCode
  | AuthErrorCode
  | GenericErrorCode;
