// One per-origin catalog per bounded context / cross-cutting concern (TD23).
// Each union, not just the object, is what error base-class constructors type their
// `code` param against (TD23 §9) — a code outside its origin's union is a compile error.

export const BookingErrorCode = {
  SERVICE_NOT_FOUND: 'BOOKING_SERVICE_NOT_FOUND',
  SERVICE_DEACTIVATED: 'BOOKING_SERVICE_DEACTIVATED',
  CLOSURE_DATE_IN_PAST: 'BOOKING_CLOSURE_DATE_IN_PAST',
  SCHEDULE_CLOSURE_NOT_FOUND: 'BOOKING_SCHEDULE_CLOSURE_NOT_FOUND',
  SCHEDULE_ALREADY_CLOSED: 'BOOKING_SCHEDULE_ALREADY_CLOSED',
  OPENING_DATE_IN_PAST: 'BOOKING_OPENING_DATE_IN_PAST',
  DAY_ALREADY_OPEN_IN_SETTINGS: 'BOOKING_DAY_ALREADY_OPEN_IN_SETTINGS',
  SCHEDULE_OPENING_ALREADY_EXISTS: 'BOOKING_SCHEDULE_OPENING_ALREADY_EXISTS',
  SCHEDULE_OPENING_NOT_FOUND: 'BOOKING_SCHEDULE_OPENING_NOT_FOUND',
  OPENING_EXCEEDS_TENANT_WINDOW: 'BOOKING_OPENING_EXCEEDS_TENANT_WINDOW',
  AVAILABILITY_DATE_IN_PAST: 'BOOKING_AVAILABILITY_DATE_IN_PAST',
  AVAILABILITY_RANGE_INVALID: 'BOOKING_AVAILABILITY_RANGE_INVALID',
  NOT_FOUND: 'BOOKING_NOT_FOUND',
  LINE_REQUIRED: 'BOOKING_LINE_REQUIRED',
  PICKUP_ADDRESS_REQUIRED: 'BOOKING_PICKUP_ADDRESS_REQUIRED',
  INVALID_TRANSITION: 'BOOKING_INVALID_TRANSITION',
  SLOT_UNAVAILABLE: 'BOOKING_SLOT_UNAVAILABLE',
  CONCURRENT_MODIFICATION: 'BOOKING_CONCURRENT_MODIFICATION',
  SERVICE_NOT_ACTIVE: 'BOOKING_SERVICE_NOT_ACTIVE',
  SERVICE_NOT_IN_TENANT: 'BOOKING_SERVICE_NOT_IN_TENANT',
  CANCELLATION_WINDOW_EXPIRED: 'BOOKING_CANCELLATION_WINDOW_EXPIRED',
  CUSTOMER_NOT_FOUND: 'BOOKING_CUSTOMER_NOT_FOUND',
  CUSTOMER_PHONE_NOT_SET: 'BOOKING_CUSTOMER_PHONE_NOT_SET',
  REJECTION_REASON_TOO_SHORT: 'BOOKING_REJECTION_REASON_TOO_SHORT',
  INFO_MESSAGE_TOO_SHORT: 'BOOKING_INFO_MESSAGE_TOO_SHORT',
  FORBIDDEN: 'BOOKING_FORBIDDEN',
  SCHEDULED_IN_PAST: 'BOOKING_SCHEDULED_IN_PAST',
  SCHEDULED_AT_INVALID: 'BOOKING_SCHEDULED_AT_INVALID',
  COMPLETE_LINES_INCOMPLETE: 'BOOKING_COMPLETE_LINES_INCOMPLETE',
  PHOTO_NOT_UPLOADED: 'BOOKING_PHOTO_NOT_UPLOADED',
  DISCOUNT_NOT_AVAILABLE: 'BOOKING_DISCOUNT_NOT_AVAILABLE',
  DISCOUNT_DISABLED: 'BOOKING_DISCOUNT_DISABLED',
  DISCOUNT_MISMATCH: 'BOOKING_DISCOUNT_MISMATCH',
  DISCOUNT_EXCEEDS_TOTAL: 'BOOKING_DISCOUNT_EXCEEDS_TOTAL',
  TENANT_ID_REQUIRED: 'BOOKING_TENANT_ID_REQUIRED',
  CREATED_BY_REQUIRED: 'BOOKING_CREATED_BY_REQUIRED',
  SERVICE_NAME_REQUIRED: 'BOOKING_SERVICE_NAME_REQUIRED',
  SERVICE_PRICE_INVALID: 'BOOKING_SERVICE_PRICE_INVALID',
  SERVICE_DURATION_INVALID: 'BOOKING_SERVICE_DURATION_INVALID',
  SERVICE_LOYALTY_POINTS_INVALID: 'BOOKING_SERVICE_LOYALTY_POINTS_INVALID',
  CLOSURE_REASON_INVALID: 'BOOKING_CLOSURE_REASON_INVALID',
  CLOSURE_TIME_RANGE_INCOMPLETE: 'BOOKING_CLOSURE_TIME_RANGE_INCOMPLETE',
  TIME_RANGE_FORMAT_INVALID: 'BOOKING_TIME_RANGE_FORMAT_INVALID',
  TIME_RANGE_ORDER_INVALID: 'BOOKING_TIME_RANGE_ORDER_INVALID',
  RESOURCE_TYPE_NOT_CREATABLE: 'BOOKING_RESOURCE_TYPE_NOT_CREATABLE',
  RESOURCE_TYPE_REF_ID_MISMATCH: 'BOOKING_RESOURCE_TYPE_REF_ID_MISMATCH',
  RESOURCE_WORKING_HOURS_OUTSIDE_TENANT_HOURS:
    'BOOKING_RESOURCE_WORKING_HOURS_OUTSIDE_TENANT_HOURS',
  RESOURCE_NO_WORKING_HOURS: 'BOOKING_RESOURCE_NO_WORKING_HOURS',
  RESOURCE_MAX_CAPACITY_INVALID: 'BOOKING_RESOURCE_MAX_CAPACITY_INVALID',
  RESOURCE_STAFF_ALREADY_WRAPPED: 'BOOKING_RESOURCE_STAFF_ALREADY_WRAPPED',
  RESOURCE_STAFF_NOT_FOUND: 'BOOKING_RESOURCE_STAFF_NOT_FOUND',
  RESOURCE_NOT_FOUND: 'BOOKING_RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_ACTIVE: 'BOOKING_RESOURCE_ALREADY_ACTIVE',
  RESOURCE_LOCATION_CANNOT_BE_DEACTIVATED: 'BOOKING_RESOURCE_LOCATION_CANNOT_BE_DEACTIVATED',
  RESOURCE_LOCATION_TYPE_IMMUTABLE: 'BOOKING_RESOURCE_LOCATION_TYPE_IMMUTABLE',
  RESOURCE_LOCATION_WORKING_HOURS_IMMUTABLE: 'BOOKING_RESOURCE_LOCATION_WORKING_HOURS_IMMUTABLE',
} as const;
export type BookingErrorCode = (typeof BookingErrorCode)[keyof typeof BookingErrorCode];

export const CustomerErrorCode = {
  NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  TENANT_ID_REQUIRED: 'CUSTOMER_TENANT_ID_REQUIRED',
  GOOGLE_OAUTH_ID_REQUIRED: 'CUSTOMER_GOOGLE_OAUTH_ID_REQUIRED',
  EMAIL_INVALID: 'CUSTOMER_EMAIL_INVALID',
  NAME_REQUIRED: 'CUSTOMER_NAME_REQUIRED',
  PHONE_INVALID: 'CUSTOMER_PHONE_INVALID',
} as const;
export type CustomerErrorCode = (typeof CustomerErrorCode)[keyof typeof CustomerErrorCode];

export const StaffErrorCode = {
  NOT_FOUND: 'STAFF_NOT_FOUND',
  ALREADY_ACTIVE: 'STAFF_ALREADY_ACTIVE',
  DEACTIVATED: 'STAFF_DEACTIVATED',
  EMAIL_MISMATCH: 'STAFF_EMAIL_MISMATCH',
  ALREADY_EXISTS: 'STAFF_ALREADY_EXISTS',
  SELF_DEACTIVATION: 'STAFF_SELF_DEACTIVATION',
  SELF_REACTIVATION: 'STAFF_SELF_REACTIVATION',
  LAST_ACTIVE_MANAGER: 'STAFF_LAST_ACTIVE_MANAGER',
  GOOGLE_ACCOUNT_CONFLICT: 'STAFF_GOOGLE_ACCOUNT_CONFLICT',
  TENANT_ID_REQUIRED: 'STAFF_TENANT_ID_REQUIRED',
  EMAIL_INVALID: 'STAFF_EMAIL_INVALID',
  NAME_REQUIRED: 'STAFF_NAME_REQUIRED',
  ROLE_INVALID: 'STAFF_ROLE_INVALID',
  GOOGLE_OAUTH_ID_REQUIRED: 'STAFF_GOOGLE_OAUTH_ID_REQUIRED',
} as const;
export type StaffErrorCode = (typeof StaffErrorCode)[keyof typeof StaffErrorCode];

export const LoyaltyErrorCode = {
  INVALID_POINTS: 'LOYALTY_INVALID_POINTS',
  INSUFFICIENT_POINTS: 'LOYALTY_INSUFFICIENT_POINTS',
  BALANCE_NOT_FOUND: 'LOYALTY_BALANCE_NOT_FOUND',
  CUSTOMER_NOT_FOUND_IN_TENANT: 'LOYALTY_CUSTOMER_NOT_FOUND_IN_TENANT',
} as const;
export type LoyaltyErrorCode = (typeof LoyaltyErrorCode)[keyof typeof LoyaltyErrorCode];

export const PlatformErrorCode = {
  SLUG_ALREADY_TAKEN: 'PLATFORM_SLUG_ALREADY_TAKEN',
  TENANT_NOT_FOUND: 'PLATFORM_TENANT_NOT_FOUND',
  TENANT_INACTIVE: 'PLATFORM_TENANT_INACTIVE',
  HOTSITE_NOT_FOUND: 'PLATFORM_HOTSITE_NOT_FOUND',
  HOTSITE_IMAGE_NOT_UPLOADED: 'PLATFORM_HOTSITE_IMAGE_NOT_UPLOADED',
  TENANT_NAME_REQUIRED: 'PLATFORM_TENANT_NAME_REQUIRED',
  TENANT_SLUG_INVALID: 'PLATFORM_TENANT_SLUG_INVALID',
  HOTSITE_NO_ENABLED_MODULES: 'PLATFORM_HOTSITE_NO_ENABLED_MODULES',
  HOTSITE_BRANDING_COLOR_INVALID: 'PLATFORM_HOTSITE_BRANDING_COLOR_INVALID',
  HOTSITE_BRANDING_OPTION_INVALID: 'PLATFORM_HOTSITE_BRANDING_OPTION_INVALID',
  HOTSITE_MODULE_TYPE_INVALID: 'PLATFORM_HOTSITE_MODULE_TYPE_INVALID',
  HOTSITE_CAROUSEL_DAYS_EXCEEDS_MAX_ADVANCE: 'PLATFORM_HOTSITE_CAROUSEL_DAYS_EXCEEDS_MAX_ADVANCE',
  HOTSITE_SEO_TITLE_TOO_LONG: 'PLATFORM_HOTSITE_SEO_TITLE_TOO_LONG',
  HOTSITE_SEO_DESCRIPTION_TOO_LONG: 'PLATFORM_HOTSITE_SEO_DESCRIPTION_TOO_LONG',
  HOTSITE_CONCURRENT_MODIFICATION: 'PLATFORM_HOTSITE_CONCURRENT_MODIFICATION',
  SETTINGS_CURRENCY_REQUIRED: 'PLATFORM_SETTINGS_CURRENCY_REQUIRED',
  SETTINGS_LANGUAGE_REQUIRED: 'PLATFORM_SETTINGS_LANGUAGE_REQUIRED',
  SETTINGS_CURRENCY_SYMBOL_INVALID: 'PLATFORM_SETTINGS_CURRENCY_SYMBOL_INVALID',
  SETTINGS_DECIMAL_PLACES_INVALID: 'PLATFORM_SETTINGS_DECIMAL_PLACES_INVALID',
  SETTINGS_FIELD_NOT_STRING: 'PLATFORM_SETTINGS_FIELD_NOT_STRING',
  SETTINGS_NOTIFICATION_EMAIL_INVALID: 'PLATFORM_SETTINGS_NOTIFICATION_EMAIL_INVALID',
  SETTINGS_LOYALTY_EXPIRY_DAYS_INVALID: 'PLATFORM_SETTINGS_LOYALTY_EXPIRY_DAYS_INVALID',
  SETTINGS_LOYALTY_EXPIRY_WARNING_DAYS_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_EXPIRY_WARNING_DAYS_INVALID',
  SETTINGS_LOYALTY_EXPIRY_WARNING_TOO_LATE: 'PLATFORM_SETTINGS_LOYALTY_EXPIRY_WARNING_TOO_LATE',
  SETTINGS_LOYALTY_NOTIFICATION_MIN_POINTS_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_NOTIFICATION_MIN_POINTS_INVALID',
  SETTINGS_LOYALTY_POINTS_PER_CURRENCY_UNIT_INVALID:
    'PLATFORM_SETTINGS_LOYALTY_POINTS_PER_CURRENCY_UNIT_INVALID',
  SETTINGS_BOOKING_CANCELLATION_WINDOW_INVALID:
    'PLATFORM_SETTINGS_BOOKING_CANCELLATION_WINDOW_INVALID',
  SETTINGS_BOOKING_MIN_ADVANCE_HOURS_INVALID: 'PLATFORM_SETTINGS_BOOKING_MIN_ADVANCE_HOURS_INVALID',
  SETTINGS_BOOKING_MAX_ADVANCE_DAYS_INVALID: 'PLATFORM_SETTINGS_BOOKING_MAX_ADVANCE_DAYS_INVALID',
  SETTINGS_BOOKING_SERVICE_BUFFER_INVALID: 'PLATFORM_SETTINGS_BOOKING_SERVICE_BUFFER_INVALID',
  SETTINGS_BOOKING_SLOT_GRANULARITY_INVALID: 'PLATFORM_SETTINGS_BOOKING_SLOT_GRANULARITY_INVALID',
  SETTINGS_BOOKING_WELCOME_STAFF_SCREEN_DAYS_INVALID:
    'PLATFORM_SETTINGS_BOOKING_WELCOME_STAFF_SCREEN_DAYS_INVALID',
  SETTINGS_TIMEZONE_INVALID: 'PLATFORM_SETTINGS_TIMEZONE_INVALID',
  SETTINGS_BUSINESS_HOURS_FORMAT_INVALID: 'PLATFORM_SETTINGS_BUSINESS_HOURS_FORMAT_INVALID',
  SETTINGS_BUSINESS_HOURS_ORDER_INVALID: 'PLATFORM_SETTINGS_BUSINESS_HOURS_ORDER_INVALID',
  SETTINGS_BUSINESS_PHONE_INVALID: 'PLATFORM_SETTINGS_BUSINESS_PHONE_INVALID',
  SETTINGS_BUSINESS_EMAIL_INVALID: 'PLATFORM_SETTINGS_BUSINESS_EMAIL_INVALID',
  SETTINGS_SOCIAL_WHATSAPP_INVALID: 'PLATFORM_SETTINGS_SOCIAL_WHATSAPP_INVALID',
  SETTINGS_CHATBOT_KNOWLEDGE_TEXT_TOO_LONG: 'PLATFORM_SETTINGS_CHATBOT_KNOWLEDGE_TEXT_TOO_LONG',
  SETTINGS_LEAD_FORM_RETENTION_MONTHS_INVALID:
    'PLATFORM_SETTINGS_LEAD_FORM_RETENTION_MONTHS_INVALID',
  SETTINGS_LEAD_FORM_MAX_SUBMISSIONS_PER_DAY_INVALID:
    'PLATFORM_SETTINGS_LEAD_FORM_MAX_SUBMISSIONS_PER_DAY_INVALID',
  SETTINGS_LEAD_FORM_MAX_SUBMISSIONS_PER_IP_PER_DAY_INVALID:
    'PLATFORM_SETTINGS_LEAD_FORM_MAX_SUBMISSIONS_PER_IP_PER_DAY_INVALID',
  SETTINGS_UPDATE_EMPTY: 'PLATFORM_SETTINGS_UPDATE_EMPTY',
  HOTSITE_UPDATE_EMPTY: 'PLATFORM_HOTSITE_UPDATE_EMPTY',
  FEATURED_PHOTO_PATH_MISMATCH: 'PLATFORM_FEATURED_PHOTO_PATH_MISMATCH',
  // Chatbot cap-rejection reasons (UC-033, docs/discovery/CHATBOT/CHATBOT.md §8) — all 5 map to
  // HTTP 429 (M19-S05 story-discovery, 2026-08-12). DAILY_CAP_REACHED covers both layer 1
  // (tenant-wide) and layer 2 (per-IP) — both are the same "come back tomorrow" outcome from the
  // visitor's perspective, matching UC-033 A1's own grouping of the two.
  CHATBOT_DAILY_CAP_REACHED: 'PLATFORM_CHATBOT_DAILY_CAP_REACHED',
  CHATBOT_CONCURRENCY_CAP_REACHED: 'PLATFORM_CHATBOT_CONCURRENCY_CAP_REACHED',
  CHATBOT_MESSAGE_CAP_REACHED: 'PLATFORM_CHATBOT_MESSAGE_CAP_REACHED',
  CHATBOT_GLOBAL_SPEND_LIMIT_REACHED: 'PLATFORM_CHATBOT_GLOBAL_SPEND_LIMIT_REACHED',
  CHATBOT_PROVIDER_BALANCE_LOW: 'PLATFORM_CHATBOT_PROVIDER_BALANCE_LOW',
  // UC-033 A4 (LLM provider call failed) — 503, distinct from the 429 cap-rejection family above.
  CHATBOT_PROVIDER_UNAVAILABLE: 'PLATFORM_CHATBOT_PROVIDER_UNAVAILABLE',
  // UC-033 A3 (message exceeds resolved maxMessageLengthChars) — 400, PR #360 review finding.
  CHATBOT_MESSAGE_TOO_LONG: 'PLATFORM_CHATBOT_MESSAGE_TOO_LONG',
  // docs/14-API_CONTRACTS.md Chatbot Widget: "404 — ... sessionId doesn't belong to this tenant".
  CHATBOT_SESSION_NOT_FOUND: 'PLATFORM_CHATBOT_SESSION_NOT_FOUND',
  // LeadFormConfig.updateQuestions() bounds (UC-037 A1/A2, docs/02-DOMAIN_MODEL.md § LeadFormConfig).
  LEAD_FORM_QUESTION_LIMIT_REACHED: 'PLATFORM_LEAD_FORM_QUESTION_LIMIT_REACHED',
  LEAD_FORM_QUESTION_OPTIONS_INVALID: 'PLATFORM_LEAD_FORM_QUESTION_OPTIONS_INVALID',
  // Defensive integrity check — two questions sharing the same client-assigned id in one save.
  LEAD_FORM_QUESTION_DUPLICATE_ID: 'PLATFORM_LEAD_FORM_QUESTION_DUPLICATE_ID',
  // M20-S02 — Lead Form submission rate-limit (docs/21-TENANTS_SETTINGS_SCHEMA.md §8). Covers
  // both the tenant-wide daily cap and the per-IP daily cap — same "come back tomorrow" outcome
  // from the submitter's perspective, matching CHATBOT_DAILY_CAP_REACHED's own grouping.
  LEAD_FORM_DAILY_CAP_REACHED: 'PLATFORM_LEAD_FORM_DAILY_CAP_REACHED',
  // M20-S05 — the public GET/POST lead-form endpoints 404 when the LEAD_FORM module is absent or
  // disabled in the tenant's hotsite layout (docs/14-API_CONTRACTS.md § Lead Form Widget).
  LEAD_FORM_NOT_ENABLED: 'PLATFORM_LEAD_FORM_NOT_ENABLED',
  // M20-S06 — GET .../submissions/:id when the id doesn't exist or belongs to a different tenant
  // (docs/14-API_CONTRACTS.md § Leads Submissions (Admin)).
  LEAD_FORM_SUBMISSION_NOT_FOUND: 'PLATFORM_LEAD_FORM_SUBMISSION_NOT_FOUND',
  // M20-S08 — mirrors HOTSITE_CONCURRENT_MODIFICATION's own version-guarded UPDATE (same gap,
  // caught the same way, on the sibling aggregate PATCH /v1/tenants/hotsite now also writes in
  // the same transaction; Codex review, PR #429).
  LEAD_FORM_CONFIG_CONCURRENT_MODIFICATION: 'PLATFORM_LEAD_FORM_CONFIG_CONCURRENT_MODIFICATION',
  // M20-S14 — Cloudflare Turnstile verification relocated here from the BFF (whose ALL_TRAFFIC
  // egress had no Cloud NAT, leaving its own outbound siteverify call with no route out).
  // Replaces the former BFF-only BFF_TURNSTILE_VERIFICATION_FAILED, removed in this same change.
  LEAD_FORM_TURNSTILE_VERIFICATION_FAILED: 'PLATFORM_LEAD_FORM_TURNSTILE_VERIFICATION_FAILED',
} as const;
export type PlatformErrorCode = (typeof PlatformErrorCode)[keyof typeof PlatformErrorCode];

export const AddressErrorCode = {
  POSTAL_CODE_INVALID: 'ADDRESS_POSTAL_CODE_INVALID',
  STATE_INVALID: 'ADDRESS_STATE_INVALID',
  NEIGHBORHOOD_REQUIRED: 'ADDRESS_NEIGHBORHOOD_REQUIRED',
  FIELD_REQUIRED: 'ADDRESS_FIELD_REQUIRED',
} as const;
export type AddressErrorCode = (typeof AddressErrorCode)[keyof typeof AddressErrorCode];

export const CountryCodeErrorCode = {
  FORMAT_INVALID: 'COUNTRY_CODE_FORMAT_INVALID',
  UNSUPPORTED: 'COUNTRY_CODE_UNSUPPORTED',
} as const;
export type CountryCodeErrorCode = (typeof CountryCodeErrorCode)[keyof typeof CountryCodeErrorCode];

export const PhoneErrorCode = {
  FORMAT_INVALID: 'PHONE_FORMAT_INVALID',
} as const;
export type PhoneErrorCode = (typeof PhoneErrorCode)[keyof typeof PhoneErrorCode];

export const MoneyErrorCode = {
  AMOUNT_INVALID: 'MONEY_AMOUNT_INVALID',
  CURRENCY_INVALID: 'MONEY_CURRENCY_INVALID',
  CURRENCY_MISMATCH: 'MONEY_CURRENCY_MISMATCH',
} as const;
export type MoneyErrorCode = (typeof MoneyErrorCode)[keyof typeof MoneyErrorCode];

export const SeoErrorCode = {
  TITLE_TOO_LONG: 'SEO_TITLE_TOO_LONG',
  DESCRIPTION_TOO_LONG: 'SEO_DESCRIPTION_TOO_LONG',
} as const;
export type SeoErrorCode = (typeof SeoErrorCode)[keyof typeof SeoErrorCode];

export const SlugErrorCode = {
  FORMAT_INVALID: 'SLUG_FORMAT_INVALID',
} as const;
export type SlugErrorCode = (typeof SlugErrorCode)[keyof typeof SlugErrorCode];

export const HexColorErrorCode = {
  FORMAT_INVALID: 'HEX_COLOR_FORMAT_INVALID',
} as const;
export type HexColorErrorCode = (typeof HexColorErrorCode)[keyof typeof HexColorErrorCode];

export const TimezoneErrorCode = {
  INVALID: 'TIMEZONE_INVALID',
} as const;
export type TimezoneErrorCode = (typeof TimezoneErrorCode)[keyof typeof TimezoneErrorCode];

export const TimeOfDayErrorCode = {
  FORMAT_INVALID: 'TIME_OF_DAY_FORMAT_INVALID',
} as const;
export type TimeOfDayErrorCode = (typeof TimeOfDayErrorCode)[keyof typeof TimeOfDayErrorCode];

export const EmailErrorCode = {
  FORMAT_INVALID: 'EMAIL_FORMAT_INVALID',
} as const;
export type EmailErrorCode = (typeof EmailErrorCode)[keyof typeof EmailErrorCode];

// Genuinely BFF-feature-originated conditions (TD23 Story 11) — guest-token/guard/tenant-lookup
// failures with no backend equivalent. Framework-level guard rejections (JWT/role/tenant-header
// mismatch, unhandled exceptions) live in AuthErrorCode instead — see its own comment below.
export const BffErrorCode = {
  GUEST_TOKEN_MISSING: 'BFF_GUEST_TOKEN_MISSING',
  GUEST_TOKEN_INVALID: 'BFF_GUEST_TOKEN_INVALID',
  GUEST_TOKEN_BOOKING_MISMATCH: 'BFF_GUEST_TOKEN_BOOKING_MISMATCH',
  GUEST_BOOKING_NOT_AWAITING_INFO: 'BFF_GUEST_BOOKING_NOT_AWAITING_INFO',
  TENANT_SLUG_HEADER_REQUIRED: 'BFF_TENANT_SLUG_HEADER_REQUIRED',
  TENANT_LOOKUP_INCONSISTENT: 'BFF_TENANT_LOOKUP_INCONSISTENT',
  STAFF_NOT_REGISTERED_IN_TENANT: 'BFF_STAFF_NOT_REGISTERED_IN_TENANT',
  CUSTOMER_NOT_REGISTERED_IN_TENANT: 'BFF_CUSTOMER_NOT_REGISTERED_IN_TENANT',
  DEV_AUTH_UNAVAILABLE: 'BFF_DEV_AUTH_UNAVAILABLE',
  UPSTREAM_UNAVAILABLE: 'BFF_UPSTREAM_UNAVAILABLE',
  // Signed OAuth `state` (M17-S32) failed to verify — tampered, expired, or missing. One
  // generic code for all three trigger conditions (docs/ENGINEERING_RULES.md § Security-sensitive
  // errors) — distinguishing them in the response would tell a forger which part of their
  // attempt failed.
  OAUTH_STATE_INVALID: 'BFF_OAUTH_STATE_INVALID',
} as const;
export type BffErrorCode = (typeof BffErrorCode)[keyof typeof BffErrorCode];

// Framework/guard-level fallbacks (TD23 Story 11, TD23 §3's "framework fallback" bucket) — not
// business-domain errors. Fires on every request that fails JwtAuthGuard/RolesGuard/TenantGuard,
// or hits ErrorInterceptor's last-resort catch-all. One union, not folded into GenericErrorCode
// (reserved for VO-less Zod validation rules — a different kind of gap) or BffErrorCode (reserved
// for BFF-feature-originated conditions with a specific business meaning).
export const AuthErrorCode = {
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  TENANT_MISMATCH: 'AUTH_TENANT_MISMATCH',
  INTERNAL_ERROR: 'AUTH_INTERNAL_ERROR',
  // Fires from ThrottlerGuard when a client exceeds a rate-limit tier (M17-S30) — a
  // framework/guard-level fallback in the same sense as the others above, not a business error.
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
} as const;
export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];

// Backs Zod validation rules with no owning VO (Story 9/10) — a small closed set reused
// across many fields via `field`/`params`, not one bespoke code per call site. A rule that
// duplicates a VO's own check must reuse that VO's code instead (see
// docs/ENGINEERING_RULES.md § Single source of truth for a validation rule's code).
export const GenericErrorCode = {
  FIELD_REQUIRED: 'GENERIC_FIELD_REQUIRED',
  VALUE_TOO_SHORT: 'GENERIC_VALUE_TOO_SHORT',
  VALUE_TOO_LONG: 'GENERIC_VALUE_TOO_LONG',
  VALUE_OUT_OF_RANGE: 'GENERIC_VALUE_OUT_OF_RANGE',
  FORMAT_INVALID: 'GENERIC_FORMAT_INVALID',
  // Enum/union/unrecognized-key mismatches — value isn't one of an allowed set/shape.
  VALUE_INVALID: 'GENERIC_VALUE_INVALID',
} as const;
export type GenericErrorCode = (typeof GenericErrorCode)[keyof typeof GenericErrorCode];

// Union of every catalogued error code across every origin (domain, VO, BFF, auth, generic) —
// the compile-time constraint for throwProblemDetail (packages/nestjs-http). Keeps its
// governance promise (an uncatalogued code fails to compile) global instead of per-context,
// while each call site still narrows to its own specific code type by inference (from
// `err.code` on a typed domain error, or from an enum member reference) — this union only
// rejects strings that aren't a member of any catalogue at all.
export type AnyErrorCode =
  | BookingErrorCode
  | CustomerErrorCode
  | StaffErrorCode
  | LoyaltyErrorCode
  | PlatformErrorCode
  | AddressErrorCode
  | CountryCodeErrorCode
  | PhoneErrorCode
  | MoneyErrorCode
  | SeoErrorCode
  | SlugErrorCode
  | HexColorErrorCode
  | TimezoneErrorCode
  | TimeOfDayErrorCode
  | EmailErrorCode
  | BffErrorCode
  | AuthErrorCode
  | GenericErrorCode;
