# modules/pubsub — Pub/Sub topics, push subscriptions + DLQs from the code's event catalog.
# Implemented in M17-S19.
#
# Source of truth: infra/terraform/pubsub-catalog.json, generated by
# `pnpm --filter @ikaro/infra-scripts run pubsub-catalog` (scans
# apps/backend/src for every GcpPubSubEventBusAdapter subscribe()/
# registerTrigger() call site — domain events and cron triggers get the
# same topic/subscription/DLQ treatment uniformly, no special-casing). CI
# fails if regenerating the file produces a diff (pr-quality.yml) — this
# module never drifts from what the code actually registers.
locals {
  catalog = jsondecode(file("${path.module}/../../pubsub-catalog.json"))

  topics = { for entry in local.catalog : entry.event => entry }

  # One entry per (topic, consumer) pair — this is the subscription/DLQ
  # granularity (DLQ topic name is "ikaro-{event}-{consumer}-dlq", per
  # consumer, not per topic).
  subscriptions = merge([
    for entry in local.catalog : {
      for consumer in entry.consumers : "${entry.event}-${consumer}" => {
        topic    = entry.event
        consumer = consumer
      }
    }
  ]...)

  # The identity Pub/Sub itself acts as when moving a failed delivery to a
  # dead-letter topic — distinct from ikaro-pubsub-invoker (the identity
  # Pub/Sub mints OIDC push tokens *as*, for delivering to the backend).
  pubsub_service_agent = "service-${var.project_number}@gcp-sa-pubsub.iam.gserviceaccount.com"
}

resource "google_pubsub_topic" "source" {
  #checkov:skip=CKV_GCP_83:MVP accepts Google-managed encryption; CMEK adds Cloud KMS operational overhead (key rotation, IAM) with no compliance driver at this stage — same rationale as modules/registry's CKV_GCP_84 skip
  for_each = local.topics

  project = var.project_id
  name    = "ikaro-${each.key}"
  labels  = var.labels
}

resource "google_pubsub_topic" "dlq" {
  #checkov:skip=CKV_GCP_83:MVP accepts Google-managed encryption; CMEK adds Cloud KMS operational overhead (key rotation, IAM) with no compliance driver at this stage — same rationale as modules/registry's CKV_GCP_84 skip
  for_each = local.subscriptions

  project = var.project_id
  name    = "ikaro-${each.value.topic}-${each.value.consumer}-dlq"
  labels  = var.labels
}

resource "google_pubsub_subscription" "push" {
  for_each = local.subscriptions

  project = var.project_id
  name    = "ikaro-${each.value.topic}-${each.value.consumer}"
  topic   = google_pubsub_topic.source[each.value.topic].id
  labels  = var.labels

  ack_deadline_seconds       = 60
  message_retention_duration = "604800s" # 7 days

  push_config {
    push_endpoint = var.backend_push_endpoint

    oidc_token {
      service_account_email = var.pubsub_invoker_sa_email
      # Explicit, not left to Pub/Sub's URL-shaped default (M17-S02's dual
      # audience validation gate) — must equal the backend's own
      # custom_audiences entry, not its real *.run.app URL.
      audience = var.backend_pubsub_audience
    }
  }

  retry_policy {
    minimum_backoff = "10s"
    maximum_backoff = "600s"
  }

  dead_letter_policy {
    dead_letter_topic     = google_pubsub_topic.dlq[each.key].id
    max_delivery_attempts = 5
  }
}

# One pull subscription per DLQ topic, purely for operator inspection
# (`gcloud pubsub subscriptions pull ikaro-<event>-<consumer>-dlq-inspect`)
# — DLQs are alert-only and never consumed by application code (S19 DLQ
# handling contract); without this, a subscriberless topic silently drops
# messages after its retention window.
resource "google_pubsub_subscription" "dlq_inspect" {
  for_each = local.subscriptions

  project = var.project_id
  name    = "ikaro-${each.value.topic}-${each.value.consumer}-dlq-inspect"
  topic   = google_pubsub_topic.dlq[each.key].id
  labels  = var.labels

  message_retention_duration = "604800s" # 7 days
}

# --- Pub/Sub service-agent IAM (required for the dead_letter_policy above
# to actually work — GCP's own documented requirement: the service agent
# needs subscriber on the subscription carrying the policy AND publisher on
# the dead-letter topic it redirects to). ---

resource "google_pubsub_subscription_iam_member" "service_agent_subscriber" {
  for_each = local.subscriptions

  project      = var.project_id
  subscription = google_pubsub_subscription.push[each.key].name
  role         = "roles/pubsub.subscriber"
  member       = "serviceAccount:${local.pubsub_service_agent}"
}

resource "google_pubsub_topic_iam_member" "service_agent_dlq_publisher" {
  for_each = local.subscriptions

  project = var.project_id
  topic   = google_pubsub_topic.dlq[each.key].name
  role    = "roles/pubsub.publisher"
  member  = "serviceAccount:${local.pubsub_service_agent}"
}

# Pub/Sub (not ikaro-pubsub-invoker itself) mints the OIDC push tokens — the
# service agent needs tokenCreator on the identity it's minting tokens as,
# or every push delivery fails auth (M17-S02 known gotcha).
resource "google_service_account_iam_member" "pubsub_sa_token_creator" {
  service_account_id = "projects/${var.project_id}/serviceAccounts/${var.pubsub_invoker_sa_email}"
  role               = "roles/iam.serviceAccountTokenCreator"
  member             = "serviceAccount:${local.pubsub_service_agent}"
}

# --- Backend publisher grants ---
# The backend is the only publisher in this system: OUTBOX_PUBLISHER for
# domain events, D3's /cron/* controllers for local/manual trigger
# re-publishing, and pull-mode publishToDlq() for the local dead-letter
# topic — granted uniformly across every topic rather than special-casing
# which subset "really" publishes where.
resource "google_pubsub_topic_iam_member" "backend_publisher" {
  for_each = local.topics

  project = var.project_id
  topic   = google_pubsub_topic.source[each.key].id
  role    = "roles/pubsub.publisher"
  member  = "serviceAccount:${var.backend_sa_email}"
}
