# modules/pubsub — Pub/Sub topics, push subscriptions + DLQs from the code's event catalog.
# Implemented in M17-S19.
#
# Source of truth: infra/terraform/pubsub-catalog.json, generated by
# `pnpm --filter @ikaro/infra-scripts run pubsub-catalog` (scans
# apps/backend/src for every GcpPubSubEventBusAdapter subscribe()/
# registerTrigger() call site — domain events and cron triggers get the
# same topic/subscription/DLQ treatment uniformly, no special-casing). CI
# fails if regenerating the file produces a diff (pr-quality.yml) — this
# module never drifts from what the code actually registers.
locals {
  catalog = jsondecode(file("${path.module}/../../pubsub-catalog.json"))

  topics = { for entry in local.catalog : entry.event => entry }

  # One entry per (topic, consumer) pair — this is the subscription/DLQ
  # granularity (DLQ topic name is "ikaro-{event}-{consumer}-dlq", per
  # consumer, not per topic). Keyed by jsonencode([event, consumer]), not a
  # hyphen-joined string — both event and consumer names already contain
  # hyphens in the real catalog (e.g. "cron-loyalty-expiry-warning"), so a
  # plain "${event}-${consumer}" join is collision-prone: two distinct pairs
  # could flatten to the same string and merge() would silently drop one
  # subscription, DLQ, and IAM grant (CodeRabbit finding, 2026-07-20).
  subscriptions = merge([
    for entry in local.catalog : {
      for consumer in entry.consumers : jsonencode([entry.event, consumer]) => {
        topic    = entry.event
        consumer = consumer
      }
    }
  ]...)

}

resource "google_pubsub_topic" "source" {
  #checkov:skip=CKV_GCP_83:MVP accepts Google-managed encryption; CMEK adds Cloud KMS operational overhead (key rotation, IAM) with no compliance driver at this stage — same rationale as modules/registry's CKV_GCP_84 skip
  for_each = local.topics

  project = var.project_id
  name    = "ikaro-${each.key}"
  labels  = var.labels
}

resource "google_pubsub_topic" "dlq" {
  #checkov:skip=CKV_GCP_83:MVP accepts Google-managed encryption; CMEK adds Cloud KMS operational overhead (key rotation, IAM) with no compliance driver at this stage — same rationale as modules/registry's CKV_GCP_84 skip
  for_each = local.subscriptions

  project = var.project_id
  name    = "ikaro-${each.value.topic}-${each.value.consumer}-dlq"
  labels  = var.labels
}

resource "google_pubsub_subscription" "push" {
  for_each = local.subscriptions

  project = var.project_id
  name    = "ikaro-${each.value.topic}-${each.value.consumer}"
  topic   = google_pubsub_topic.source[each.value.topic].id
  labels  = var.labels

  ack_deadline_seconds       = 60
  message_retention_duration = "604800s" # 7 days

  # Never expire from inactivity (GCP default: auto-delete after 31 idle
  # days). A genuinely low-traffic topic (e.g. StaffInvited) can plausibly
  # see no messages for a month — losing the subscription would silently
  # drop everything published in the gap before the next apply recreates it
  # (CodeRabbit finding, 2026-07-20).
  expiration_policy {
    ttl = ""
  }

  push_config {
    push_endpoint = var.backend_push_endpoint

    oidc_token {
      service_account_email = var.pubsub_invoker_sa_email
      # Explicit, not left to Pub/Sub's URL-shaped default (M17-S02's dual
      # audience validation gate) — must equal the backend's own
      # custom_audiences entry, not its real *.run.app URL.
      audience = var.backend_pubsub_audience
    }
  }

  retry_policy {
    minimum_backoff = "10s"
    maximum_backoff = "600s"
  }

  dead_letter_policy {
    dead_letter_topic     = google_pubsub_topic.dlq[each.key].id
    max_delivery_attempts = 5
  }
}

# One pull subscription per DLQ topic, purely for operator inspection
# (`gcloud pubsub subscriptions pull ikaro-<event>-<consumer>-dlq-inspect`)
# — DLQs are alert-only and never consumed by application code (S19 DLQ
# handling contract); without this, a subscriberless topic silently drops
# messages after its retention window.
resource "google_pubsub_subscription" "dlq_inspect" {
  for_each = local.subscriptions

  project = var.project_id
  name    = "ikaro-${each.value.topic}-${each.value.consumer}-dlq-inspect"
  topic   = google_pubsub_topic.dlq[each.key].id
  labels  = var.labels

  message_retention_duration = "604800s" # 7 days

  # Operator-only — can plausibly go months between pulls (only used when a
  # delivery actually fails). Without this, GCP's default 31-day inactivity
  # expiration deletes exactly the subscription the DLQ handling contract
  # depends on to keep the DLQ topic from silently dropping messages
  # (CodeRabbit finding, 2026-07-20).
  expiration_policy {
    ttl = ""
  }
}
