export enum NotificationTemplateKey {
  BOOKING_REQUESTED_ADMIN = 'booking-requested-admin',
  BOOKING_REQUESTED_CUSTOMER = 'booking-requested-customer',
  BOOKING_APPROVED_CUSTOMER = 'booking-approved-customer',
  BOOKING_REJECTED_CUSTOMER = 'booking-rejected-customer',
  BOOKING_INFO_REQUESTED_CUSTOMER = 'booking-info-requested-customer',
  BOOKING_INFO_SUBMITTED_ADMIN = 'booking-info-submitted-admin',
  BOOKING_CANCELLED_CUSTOMER = 'booking-cancelled-customer',
  BOOKING_CANCELLED_ADMIN = 'booking-cancelled-admin',
  BOOKING_RESCHEDULED_CUSTOMER = 'booking-rescheduled-customer',
  BOOKING_RESCHEDULED_ADMIN = 'booking-rescheduled-admin',
  BOOKING_REMINDER_DUE = 'booking-reminder-due',
  BOOKING_REMINDER_DUE_TODAY = 'booking-reminder-due-today',
  ADMIN_DAILY_SCHEDULE_REMINDER = 'admin-daily-schedule-reminder',
  SERVICE_POINTS_EARNED = 'service-points-earned',
  POINTS_EXPIRING_SOON = 'points-expiring-soon',
  STAFF_INVITATION = 'staff-invitation',
}
